### ISSUE TITLE
Fast travel not available without the Input Mod

### ISSUE THREAD

**Issue by PiKeyAr** [Sora-yx/SADX-Better-Tails-AI#1]
The fast travel feature is currently mapped to the C button, which isn't normally accessible to the player unless the Input Mod is enabled and the button is configured in it. To improve compatibility I'd suggest replacing this with some kind of button combination that doesn't involve C or Z buttons.

Also, in the [release notes](https://github.com/Sora-yx/SADX-Better-Tails-AI/releases/tag/2.1) for the latest version it says "press LT/L1" for the fast travel feature, which got me confused until I looked at the source code. L1 and R1 are default XInput bindings in the Input Mod that map the shoulder buttons to the unused C and Z buttons in SADX. The actual game only has a single set of triggers and no shoulder buttons.

**Comment by PiKeyAr** [comment]
Also, for selecting the destination it checks for `Buttons_Up` and `Buttons_Down`, which normally aren't mapped either. They're only used internally on some menu screens. It may be a better idea to use the second analog stick that is mapped to first person camera in the vanilla game. Otherwise it's impossible to use the feature without the D-Pad mapped in the Input Mod.

**Comment by Sora-yx** [comment]
Fixed in the last update.
