### ISSUE TITLE
Crash at njSubVector call

### ISSUE THREAD

**Issue by PiKeyAr** [Sora-yx/SADX-Better-Tails-AI#2]
![image](https://user-images.githubusercontent.com/23312549/112314246-253f2d80-8cec-11eb-988c-7c8755e246fe.png)
To reproduce, use the Test Spawn mod and the following command line:
`sonic -l 1 -p -248 1 125`
It has a chance of crashing when the rhinotank hits the player. If it doesn't crash, quit the game and run the command line again. It may be difficult to reproduce. Sometimes it crashes several times in a row, other times I couldn't get it to crash for a while. But it does eventually crash, and I was able to trigger it when only this mod was enabled besides Test Spawn. I think it has something to do with Sonic dying?
Crash details:
`Unhandled exception at 0x00787612 in sonic.exe: 0xC0000005: Access violation reading location 0x00000020.`

**Comment by Sora-yx** [comment]
Thanks for the report, I drafted a new update which hopefully fixed it.
This was related to the Second Chance feature (which is random, that's why you didn't get the crash consistently.)
